# Generated by Django 5.2.17 on 2026-08-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_alter_question_options_question_unique_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(choices=[(4, '是'), (2, '有時'), (0, '否')]),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_submission_question'),
        ),
    ]
