# Generated by Django 5.2.17 on 2026-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_alter_answer_score_answer_unique_submission_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('emotional', 'Emotional'), ('social', 'Social')], max_length=64),
        ),
    ]
