# Generated by Django 5.2.17 on 2026-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_alter_question_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['emotional', 'social'])), name='category_must_be'),
        ),
    ]
