# Generated by Django 5.2.17 on 2026-09-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_question_category_must_be'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('score__in', [4, 2, 0])), name='score_must_be'),
        ),
    ]
