# Generated by Django 5.2.17 on 2026-09-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0007_alter_answer_question_alter_answer_submission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-created_at'], name='user_created_at_index'),
        ),
    ]
