# Generated by Django 5.2.17 on 2026-09-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0008_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaire_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
