# Generated by Django 5.2.17 on 2026-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0009_alter_questionnaire_questionnaire_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(choices=[(4, '常常'), (2, '有時'), (0, '從未')]),
        ),
    ]
