# Generated by Django 5.2.17 on 2026-09-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0010_alter_answer_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('question_number',)},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created_at',)},
        ),
    ]
